version: '2.1'

volumes:
    loki_data: {}
    grafana_data: {}

services:
  
  grafana:
    image: grafana/grafana:master
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_EXPLORE_ENABLED=true
    restart: unless-stopped
    expose:
      - 3000
    labels:
      org.label-schema.group: "monitoring"

  loki:
    image: qxip/victorialogs
    container_name: loki
    restart: unless-stopped
    volumes:
      - loki_data:/var/lib/victoria-metrics
    expose:
      - 3100
    ports:
      - "3100:8401"
    labels:
      org.label-schema.group: "monitoring"
